# Generated by Django 4.2.4 on 2023-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sec_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("groups", models.CharField(max_length=50)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("logentry", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("user_permissions", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("query", models.CharField(max_length=50)),
            ],
        ),
    ]
