# Generated by Django 4.2.4 on 2023-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sec_app", "0002_search"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="search",
            name="email",
        ),
        migrations.RemoveField(
            model_name="search",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="search",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="search",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="search",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="search",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="search",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="search",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="search",
            name="logentry",
        ),
        migrations.RemoveField(
            model_name="search",
            name="password",
        ),
        migrations.RemoveField(
            model_name="search",
            name="query",
        ),
        migrations.RemoveField(
            model_name="search",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="search",
            name="username",
        ),
        migrations.AddField(
            model_name="search",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="search",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="search",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
