# Generated by Django 4.2.4 on 2023-08-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sec_app", "0003_remove_search_date_joined_remove_search_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
