# Generated by Django 4.2.4 on 2023-08-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_sec_app", "0004_uploadfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadfile",
            old_name="file_name",
            new_name="name",
        ),
    ]
